server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accounts
  data:
    mongodb:
      uri: mongodb+srv://demo_user:Feltaoui581@storefront-cluster-m0-ojqiy.gcp.mongodb.net/accounts
  kafka:
    bootstrap-servers: pkc-4r297.europe-west1.gcp.confluent.cloud:9092
    topic:
      accounts-customer: accounts.customer.change
    consumer:
      group-id: accounts
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
---
server:
  port: 8080
spring:
  profiles: gke
logging:
  level:
    root: INFO
